### ISSUE TITLE
Different color for different Lat/Lng - Possible?

### ISSUE THREAD

**Issue by mkesavan13** [unchartedsoftware/salt#114]
Hi Salt team,

I have the following Scenario,

> Need to plot temperatures over a map. For each temperature range, it could take any of 252 RGB colors (Different shades to differentiate temperatures). How should I go about this? Creating 252 layers with zooms looks impossible. What is the suggested approach? Is it possible to have one layer which can have different colors for different lat/lng?

Kindly help me.

Thank you.

**Comment by Ghnuberath** [comment]
Hi there,

Can you give me a little more information about your question? You have a temperature range (i.e. T1 -> T1+251) and you want to use 252 distinct shades to plot those values?

If my above interpretation of what you're saying is correct, then here's a possible solution:
1. Use the MeanAggregator to calculate the average temperature at a certain lat/lng
2. You'll note that the salt-examples use "color ramps" to represent values at a certain location (it's usually some form of gradient). You could render your average temperature values using a colour ramp which selects from 252 shades based on the mean temperature at a location.

If I'm not interpreting your question correctly, please let me know how you're looking to aggregate the temperatures at a given lat/lng. If not mean(), then what function?

**Comment by mkesavan13** [comment]
Hi Sean,

Thank you for getting back. Yes. You're interpretation is correct. However, let me explain the scenario in detail. 
1. I have 252 Temperature ranges -> 252 Colours like Range A to B -> Colour 1, B to C -> Colour 2, C to D -> Colour 3 and so on.
2. Current idea we have, is to query 252 ranges separately and use 252 colors which will add 252 Layers, which is time consuming. 
**3. We would like to have a single Layer wherein temperatures of range A to B will have Colour 1, temperatures of range B to C will have Colour 2, temperatures of C to D will have Colour 3 and so on.**

As quoted by you,
> You could render your average temperature values using a colour ramp which selects from 252 shades based on the mean temperature at a location.

Could you explain in detail, **Which piece of code handles, which color goes to which Latitude/ Longitude?**

**Example:**

Even if we have to consider 10 to 20 colors/ranges, instead of 252, currently we are in a situation to create more number of layers. 

if we have 5 categories of temperatures for 10 Years data, we end up creating,

5 (categories) * 10 (years) * 12 (months) = 600 * 20 (ranges/ colors) = 12000 layers.

**If we have an alternative method to plot different colors for different Latitude and Longitude with in one layer, it would be helpful. Do we have such possibility? If so, please let us know how?**

So instead of 12000 layers, we will only create 600 layers.

Kindly help me.

**Comment by Ghnuberath** [comment]
Hi there. Absolutely you have the ability to plot different colours in a single layer - this is something we do very often.

Salt tiling is a multi-step process which can lead you to what you want to create. When talking about heatmaps, Salt will create a tiled visualization where every pixel corresponds to a lat/lng square (the size of which is contingent on your zoom level), and the colour of which is determined by the aggregated values which fall into that square.

**Step 1:** Choose your projection (i.e. `MercatorProjection`) and your coordinate extractor (`cExtractor`), which together determine where (*i.e. which pixels at which zoom levels*) a a certain row in your source data set will appear in the resulting visualization. I think you've got a good handle on this part.

**Step 2:** Choose your value column (`vExtractor`) and `Aggregator`. *Step 1* will most definitely assign multiple source data rows to the same pixel. **You** decide how to turn them into a single value using an `Aggregator`. In this case, I'm assuming that you have source data that looks something like this:

```
| lng   | lat   | temperature|
| 79    | 43   | 21                |
| 79.2 | 43   | 23                |
...
```

As part of **Step 2**, you have to choose an `Aggregator` which will take the group of temperatures which fall into the same pixel and turn them into a single value. Perhaps the `mean()` temperature? In which case you'd be using the `MeanAggregator`.

**Step 3:** At this point, you've defined everything you need to generate a Salt tile. Salt tiles **are not visual**. Rather, they are collections of data which *you* use to generate a visual representation. In this case, I'll assume you've defined a `Series` like this (modified from the PNG example):

```scala
val cExtractor = (r: Row) => {
    // assuming a table structure like my simple example above, 
    // you'll be extracting (lng, lat) at cols (0,1) as coordinates
    if (r.isNullAt(0) || r.isNullAt(1)) {
      None
    } else {
      Some((r.getDouble(0), r.getDouble(1)))
    }
}

val vExtractor = (r: Row) => {
  // assuming temperature is a Double at column 2
  if (r.isNullAt(0)) {
    None
  } else {
    Some(r.getDouble(2))
  }
}

val temps = new Series((255, 255),
        cExtractor,
        new MercatorProjection(level),
        vExtractor,
        MeanAggregator,
        Some(MinMaxAggregator))
```

When you tile this `Series`, you'll have tiles which are 256x256 values, where every value is the average temperature at that pixel at that zoom level in that tile (much like in the current PNG example, how every pixel is the count of total taxi trips starting at that pixel at that zoom level in that tile).

THIS is when you decide what colours to assign to the values (and, incidentally, *this has very little to do with Salt*).

In the current PNG example, we use a logarithmic function to scale the pickups count at a pixel to a value between `0` and `1`. Then we assign a colour to that pixel based on that `[0,1]` value and a "ramp" (a gradient defined in `interpolateColor()`).

In your case, you'll want  to do something more complex than a simple logarithmic gradient. Rather than doing a logarithmic transformation on the value, you might convert it to an integer between `[0,N]`, where `N` is the number of colors you want to use (so maybe `[0,251]`?). Then, alter `interpolateColor()` and make it choose one of `252` colors stored in a `Seq` based on the integer `[0,251]`. At the end, you'll have a zoomable, tiled visualization which assigns one of `252` colors to every pixel based on the mean temperature at that pixel, all in a single layer.

**Comment by mkesavan13** [comment]
Sean,

Thank you so much for your kind and detailed response. It worked like a charm. **vExtractor** and **MeanAggregator** were the ones that helped much in identifying the need.

**Comment by Ghnuberath** [comment]
Glad to hear it!
